### ISSUE TITLE
Update scope type modifier to expand on both ends

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#484]
Right now you can take lines paragraphs and soon non whitespace sequences that expands from both anchor and active of the selection. Currently containing scopes only use start off the selection.

I want both of these to have the same result. (air and bat are in different functions)
`take funk air past bat`
`take air past bat take funk`

I was thinking that we could implement this first thing in the selection/scope modifier by basically calling the specific implementation twice, once for both ends. To day we pass the entire selection to the specific modifier(line, funk, ...). What if we pass in a single position instead?

```js
const startSelection = getSelectionForScope(selection.start, "function"); // function is of course a variable
if (selection.isEmpty() 
  || getNodeAtLocation(selection.start).id === getNodeAtLocation(selection.end).id) {
    return startSelection;
}
const endSelection = getSelectionForScope(selection.end, "function");
return  getSelectionFromPositions(startSelection.start, endSelection.end);
```

- [ ] Add test for https://github.com/pokey/cursorless-vscode/issues/484#issuecomment-1013856057
- [ ] Add test for "funk wrap that" with `that` mark starting in one statement and ending in another (see https://github.com/cursorless-dev/cursorless/issues/883)
- [ ] Add test for "snip funk after that" with `that` mark starting in one function and ending in another (see https://github.com/cursorless-dev/cursorless/issues/883)
- [ ] https://github.com/cursorless-dev/cursorless/issues/901

## _edit (@pokey)_

Let's implement this one in a new `ContainingScope` stage that all containing scopes share.  The algorithm should be as described in https://github.com/cursorless-dev/cursorless/pull/629#issuecomment-1136090441.  The initial implementation will be folded into https://github.com/cursorless-dev/cursorless/pull/629

**Comment by pokey** [comment]
I don't think this will work for "round", even if we decide to make it consistent with "funk". The problem is if the user has `(())`, and says "take round repper", referring to the first `)`. When expanding from the end, it will look right and end up with the whole string, which is incorrect

**Comment by AndreasArvidsson** [comment]
Yes some special handling of matching pairs is fine. Just getting all the containing scope and selection types working as one would be nice.
