### ISSUE TITLE
Migrate to a pnpm monorepo

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#945]
# The problem

All of the Cursorless code exists as part of the VSCode extension and has many references to `vscode`.  We'd like to abstract away VSCode and turn Cursorless into a generic npm package to enable the following:

- #435 to support Cursorless in other IDEs
- Allow other applications (eg [rango](https://github.com/david-tejada/rango), MS Word plugin) to leverage the Cursorless engine
- Embed Cursorless in Talon for OCR-based global hats
- Support Cursorless VSCode on the web
- Share code with our docs site, which would enable one source of truth between docs and code
- Allow us to fake / mock pieces of VSCode to enable proper unit testing (today nearly all Cursorless tests are end-to-end)

# The solution

~~We'd like to migrate to [nx](https://nx.dev/).~~ Let's use pnpm

## Experiments to run

- [x] When you do auto-import in VSCode, does it look at `node_modules` of the package containing the file you're doing auto-import from even if your VSCode workspace is opened to the root directory of the project?
- [x] When you do a rename, will it apply across package boundaries?

## To discuss

- [x] What to do about type imports?

## Todo

- [x] Enforce pnpm https://www.npmjs.com/package/only-allow
- [x] Setup [syncpack](https://jamiemason.github.io/syncpack/fix-mismatches) to ensure we use consistent versions
- [x] Run typescript scripts directly rather than after compiling?  could use https://github.com/esbuild-kit/tsx or https://bun.sh/
- [x] Meta-updater to keep references + other stuff in tsconfig / package.json up to date
  - https://github.com/pnpm/meta-updater
  - https://github.com/pnpm/pnpm/blob/main/.meta-updater/src/index.ts
- [x] Consider wireit (https://github.com/google/wireit) or turborepo for building / caching

## **old** We'll proceed as follows

- [x] Superficial transformation where we convert Cursorless to an nx repo, but keep all of the extension code in a single nx app.  Note that the current `cursorless-nx` directory will become the root of the repo
- [x] Migrate the `website` directory to a `docs` nx app.  Not sure exactly how to get docusaurus to work as an nx app
- [x] Migrate pieces of the Cursorless core to nx libraries as needed for using them in docs site or #435.  Note that we'll rely on the abstractions introduced in https://github.com/cursorless-dev/cursorless/tree/main/src/ide to abstract away VSCode
- [x] Run [`nx migrate`](https://nx.dev/core-features/automate-updating-dependencies) to get up to date
